🔨 script : cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -31,10 +31,10 @@ jobs:
             
             docker-compose -f docker-compose.prod.yml up -d                                                   # 새 컨테이너 배포
             
-            sleep 10
-            if ! curl -f http://localhost:8080/actuator/health; then
-              echo "Health check failed. Rolling back..."
-              docker-compose -f docker-compose.prod.yml down
-              docker-compose -f docker-compose.rollback.yml up -d
-              exit 1
-            fi
+#            sleep 10
+#            if ! curl -f http://localhost:8080/actuator/health; then
+#              echo "Health check failed. Rolling back..."
+#              docker-compose -f docker-compose.yml down
+#              docker-compose -f docker-compose.rollback.yml up -d
+#              exit 1
+#            fi
